import { forwardRef } from 'react'
import LeafGuardLogo from '../ui/LeafGuardLogo.jsx'
import DiagnosisCard from '../results/DiagnosisCard.jsx'
import TopPredictions from '../results/TopPredictions.jsx'
import DescriptionCard from '../results/DescriptionCard.jsx'
import SymptomsCard from '../results/SymptomsCard.jsx'
import CausesCard from '../results/CausesCard.jsx'
import PreventionCard from '../results/PreventionCard.jsx'
import TreatmentCard from '../results/TreatmentCard.jsx'
import RecommendedAction from '../results/RecommendedAction.jsx'
import WeatherAdvisory from '../results/WeatherAdvisory.jsx'

const HEALTHY_MAINTENANCE_TIPS =
  'Continue regular monitoring, water appropriately at the root level, maintain proper plant spacing, inspect leaves periodically, and keep good airflow around the canopy.'

const HEALTHY_DESCRIPTION_FALLBACK =
  'No visible disease symptoms were detected on this leaf. The plant tissue appears healthy and vigorous.'

export function Header({ generatedDate, generatedTime }) {
  return (
    <div className="pdf-header flex items-center justify-between border-b border-black/10 pb-5 mb-2 shrink-0">
      <div className="flex items-center gap-3">
        <LeafGuardLogo size={36} />
        <div>
          <h1 className="text-xl font-bold font-display text-ink leading-tight">LeafGuard</h1>
          <p className="text-xs text-primary font-mono font-medium">
            AI Plant Disease Detection Report
          </p>
        </div>
      </div>
      <div className="text-right">
        <p className="text-[11px] text-ink/40 font-mono uppercase tracking-wider mb-0.5">
          Generated on
        </p>
        <p className="text-sm font-semibold font-mono text-ink">{generatedDate}</p>
        <p className="text-xs font-mono text-ink/60">{generatedTime}</p>
      </div>
    </div>
  )
}

export function Footer() {
  return (
    <div className="pdf-footer pt-4 border-t border-black/10 text-center flex flex-col items-center justify-center gap-1 text-ink/50 mt-auto shrink-0">
      <p className="text-xs font-semibold text-ink/70">
        Generated by LeafGuard • Built by Sarthak
      </p>
      <p className="text-[11px] text-ink/40 leading-relaxed max-w-lg">
        This report is AI-generated and intended for informational purposes only.
      </p>
    </div>
  )
}

export function PDFPage({
  children,
  isFirstPage = false,
  isLastPage = false,
  generatedDate,
  generatedTime,
}) {
  return (
    <div
      className="pdf-page w-[800px] h-[1131px] min-h-[1131px] max-h-[1131px] bg-[#F9FBF8] text-ink p-10 flex flex-col justify-between box-border font-sans leading-normal overflow-hidden relative"
      style={{ fontFamily: '"Plus Jakarta Sans", sans-serif' }}
    >
      <div className="flex flex-col gap-5 flex-1 justify-start">
        {isFirstPage && <Header generatedDate={generatedDate} generatedTime={generatedTime} />}
        <div className="flex flex-col gap-5">{children}</div>
      </div>
      {isLastPage && <Footer />}
    </div>
  )
}

const PDFReport = forwardRef(function PDFReport(
  { result, uploadedImage, generatedDate, generatedTime, pages = null },
  ref
) {
  if (!result) return null

  const prediction = result?.prediction
  const details = prediction?.details

  const isHealthy = result.success && details?.severity === 'Healthy'
  const isDiseased = result.success && details?.severity !== 'Healthy'

  const imageSrc = uploadedImage || '/sample-images/tomato-healthy.jpg'

  // Build section map
  const sections = {
    image: imageSrc ? (
      <div
        key="image"
        data-pdf-section="image"
        className="flex flex-col items-center justify-center p-5 rounded-xl2 bg-white border border-black/5 shadow-card"
      >
        <p className="text-xs font-mono font-semibold uppercase tracking-wide text-ink/40 mb-3">
          Analyzed Leaf Sample
        </p>
        <div className="w-[250px] h-[250px] rounded-xl bg-white border border-black/5 p-2 flex items-center justify-center shadow-inner overflow-hidden">
          <img
            src={imageSrc}
            alt="Analyzed Leaf"
            className="w-full h-full object-contain rounded-lg"
            crossOrigin="anonymous"
          />
        </div>
      </div>
    ) : null,

    diagnosis: (
      <div key="diagnosis" data-pdf-section="diagnosis">
        <DiagnosisCard
          plant={details?.plant}
          disease={prediction?.display_name}
          confidence={prediction?.confidence}
          severity={details?.severity}
        />
      </div>
    ),

    row1: (
      <div key="row1" data-pdf-section="row1" className="grid grid-cols-2 gap-5 items-stretch">
        <TopPredictions predictions={result?.top_predictions} />
        <DescriptionCard
          description={
            isHealthy
              ? details?.description || HEALTHY_DESCRIPTION_FALLBACK
              : details?.description
          }
        />
      </div>
    ),

    row2: isDiseased ? (
      <div key="row2" data-pdf-section="row2" className="grid grid-cols-2 gap-5 items-stretch">
        <SymptomsCard symptoms={details?.symptoms} />
        <CausesCard causes={details?.causes} />
      </div>
    ) : null,

    row3: isDiseased ? (
      <div key="row3" data-pdf-section="row3" className="grid grid-cols-2 gap-5 items-stretch">
        <PreventionCard prevention={details?.prevention} />
        <TreatmentCard treatment={details?.treatment} />
      </div>
    ) : null,

    action: (
      <div key="action" data-pdf-section="action">
        <RecommendedAction
          action={
            isHealthy
              ? details?.recommended_action || HEALTHY_MAINTENANCE_TIPS
              : details?.recommended_action
          }
        />
      </div>
    ),

    weather:
      result?.weather || result?.weather_advisory ? (
        <div key="weather" data-pdf-section="weather">
          <WeatherAdvisory weather={result?.weather} advisory={result?.weather_advisory} />
        </div>
      ) : null,
  }

  // Paginated export mode
  if (pages && pages.length > 0) {
    return (
      <div ref={ref} className="pdf-report-root flex flex-col gap-0">
        {pages.map((pageSectionKeys, pageIdx) => {
          const isFirstPage = pageIdx === 0
          const isLastPage = pageIdx === pages.length - 1
          return (
            <PDFPage
              key={pageIdx}
              isFirstPage={isFirstPage}
              isLastPage={isLastPage}
              generatedDate={generatedDate}
              generatedTime={generatedTime}
            >
              {pageSectionKeys.map((key) => sections[key])}
            </PDFPage>
          )
        })}
      </div>
    )
  }

  // Unpaginated measurement mode
  return (
    <div
      ref={ref}
      className="pdf-report-measure w-[800px] bg-[#F9FBF8] text-ink p-10 flex flex-col gap-5 font-sans leading-normal"
      style={{ fontFamily: '"Plus Jakarta Sans", sans-serif' }}
    >
      <div data-pdf-section="header">
        <Header generatedDate={generatedDate} generatedTime={generatedTime} />
      </div>
      {sections.image}
      {sections.diagnosis}
      {sections.row1}
      {sections.row2}
      {sections.row3}
      {sections.action}
      {sections.weather}
      <div data-pdf-section="footer">
        <Footer />
      </div>
    </div>
  )
})

export default PDFReport
